#!/usr/bin/env bash
set -e

UNAME=$(uname)

case $UNAME in
    Linux)
        OS="linux"
        ;;
    Darwin)
        OS="mac"
        ;;
    *)
        echo "Unsupported OS, exiting"
        exit
        ;;
esac


CONFIG="$OS.install.conf.yaml"
DOTBOT_DIR=".dotbot"
echo $CONFIG
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"


if [ ! -e $HOME/.gitconfig-user ]; then
    read -p "git user: " git_user
    read -p "git email: " git_mail
    echo "[user]" > $HOME/.gitconfig-user
    echo "name = $git_user" >> $HOME/.gitconfig-user
    echo "email = $git_mail" >> $HOME/.gitconfig-user
fi


