#!/usr/bin/env bash

set -e

CONFIG=".install.conf.yaml"
DOTBOT_DIR=".dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"


if [ ! -e $HOME/.gitconfig-user ]; then
    read -p "git user: " git_user
    read -p "git email: " git_mail
    echo "[user]" > $HOME/.gitconfig-user
    echo "\tname = $git_user" >> $HOME/.gitconfig-user
    echo "\temail = $git_mail" >> $HOME/.gitconfig-user
fi


